// All projects, people, files and services here are invented teaching examples.
const make=(id,title,discipline,group,person,arrival,files,from,to,question,choices,reviewers,candidate,checklist,hold='',sample='')=>({id,title,discipline,group,person,arrival,files,from,to,question,choices,reviewers,candidate,checklist,hold,sample});
export const scenarios={
 'oral-heritage':make('oral-heritage','Oral histories','History','Living Heritage Collective','Dr Tova Mer','Today your group corrected transcripts and wants to describe the collection. The recordings came with limited consent and community rules. Even a catalogue title might reveal something the community wants kept private.','600 GiB of voice recordings, transcript text and scanned images. Invented file names: clip-EXAMPLE.wav, transcript-EXAMPLE.txt, image-EXAMPLE.tiff. No voices or words appear here.','recordings-v1','curated-collection-v2','Who should decide whether anyone can find the description?',[
 {id:'publish',label:'Put up a public catalogue title now',cue:'A title might seem harmless.',feedback:'A catalogue title can reveal a person, place or tradition even when recordings stay closed. Take the title back for community review first.',good:false},
 {id:'private',label:'Keep the description private forever',cue:'No one could find it.',feedback:'Keeping it private for now is safe, but the community should decide future discoverability. Ask its appointed reviewer rather than deciding for them.',good:false},
 {id:'ask',label:'Keep it private and ask the appointed reviewers',cue:'Description and file requests are separate questions.',feedback:'Keep the description private while the steward checks the change, the privacy reviewer checks limited consent and the community-appointed reviewer considers discovery. No file access follows from a title.',good:true}],['steward','privacy','community'],'Meridian Community-Governed Collection','List the invented files; request a check that copies stay unchanged; keep the description private; ask separately who may request recordings.','','transcript_id,language,consent_status (headers only)'),
 'stellar-survey':make('stellar-survey','Sky survey','Astronomy','Sky Survey Lab','Dr Ada Rell','The lab corrected a sky mosaic today. Another scientist wants the corrected images, but the processing run has not been linked to them. The collection is too large to assume an archive can take it.','120,000 GiB of sky images in FITS and Zarr formats. Invented files: tile-EXAMPLE.fits, tile-EXAMPLE.zarr and pipeline-run-EXAMPLE.txt. No image pixels appear here.','sky-raw-v1','sky-calibrated-v2','What would let someone understand and store this correction?',[
 {id:'copy',label:'Send the corrected images alone',cue:'The pictures look ready.',feedback:'Without the processing run and calibration inputs, a colleague cannot explain the correction. Record the run and ask about archive capacity.',good:false},
 {id:'run',label:'Link the run and ask about archive capacity',cue:'The copy and its origin travel together.',feedback:'That connects old and new images to the method. The steward still checks the link and a curator must check space and file integrity.',good:true},
 {id:'wait',label:'Wait until every image has been checked',cue:'Checking files matters.',feedback:'Checks matter, but waiting does not record which run made the new images. Link the run first and arrange the checks.',good:false}],['steward'],'Meridian Large-Object Archive','List FITS and Zarr objects; check processing history, file integrity and capacity.','','FITS header sketch: SIMPLE = T; pixels omitted'),
 'neighbourhood-voices':make('neighbourhood-voices','Neighbourhood interviews','Social science','Urban Lives Group','Dr Malik Osei','Your team coded interviews about neighbourhood change today. The coded table sits beside voice recordings and a codebook. Interviewees agreed only to limited uses, so a coded row is not automatically safe to publish.','80 GiB of recordings, text and coded tables. Invented files: audio-EXAMPLE.wav, codebook-EXAMPLE.csv and memo-EXAMPLE.txt. No names or quotes appear here.','interviews-v1','coded-interviews-v2','Does coding the interviews make the result public?',[
 {id:'post',label:'Publish the coded table',cue:'It has no direct names.',feedback:'Codes can still point to someone, and limited consent does not become open consent when you code a table. Ask the privacy reviewer about this use.',good:false},
 {id:'delete',label:'Discard the codebook',cue:'Fewer files might feel safer.',feedback:'Without the codebook, others cannot understand what the codes mean. Keep it restricted and ask which use consent covers.',good:false},
 {id:'scope',label:'Keep the table private and check the agreed use',cue:'The agreed purpose matters.',feedback:'That protects both the recordings and the coded table while a privacy reviewer examines the limited consent. A private description is separate from file access.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List recordings, coded tables and codebook; ask about the agreed use; keep descriptions private; check file integrity.','','recording_id,codebook_version,consent_scope (headers only)'),
 'coastal-species':make('coastal-species','Coastal species','Ecology','Coastal Ecology Unit','Dr Paz Linn','The team replaced exact rare-species sites with larger grid cells today. A published map could still reveal sites when combined with other information. No outside location-risk assessment has happened.','300 GiB of restricted tables and map images. Invented files: restricted-EXAMPLE.csv, grid-EXAMPLE.csv and preview-EXAMPLE.tiff. No coordinates or sightings appear here.','observations-v1','generalised-coordinates-v2','Is a coarser map safe to share?',[
 {id:'map',label:'Publish the coarser map now',cue:'The exact points are gone.',feedback:'A grid cell or map caption can still narrow down a rare site. An outside location-risk assessment must happen before release.',good:false},
 {id:'source',label:'Share the raw sites instead',cue:'Others could check the work.',feedback:'Exact sites create more risk. Keep the source restricted and ask an independent specialist to assess the coarser map and its description.',good:false},
 {id:'assess',label:'Keep both private and request a location-risk check',cue:'The map and its description both matter.',feedback:'The steward can trace the grid method, but only an outside location-risk assessment can resolve the release question. This exercise cannot clear that hold.',good:true}],['steward','privacy'],'Meridian General Archive','Keep raw sites apart from the grid; document the method; request an outside location-risk assessment before release.','An independent ecology location-risk specialist has not assessed the map and its description.','species_code,grid_cell,observation_month (headers only)'),
 'variant-study':make('variant-study','Variant study','Genomics','Human Variation Group','Dr Elin Roe','The group wants to reprocess a very large sequence collection today. A secure vault might hold the files, but the consent status is unknown. Storage capacity says nothing about whether this reuse is allowed.','40,000 GiB of sequence reads and variant calls. Invented files: reads-EXAMPLE.fastq, variants-EXAMPLE.vcf and run-EXAMPLE.txt. No genotypes or participant IDs appear here.','sequence-v1','variant-calls-v2','Does a suitable vault allow reprocessing or sharing?',[
 {id:'vault',label:'Use the secure vault and proceed',cue:'The files would stay protected.',feedback:'The vault may fit the files, but it cannot supply missing consent or an approved purpose. Pause reuse and refer the question to the responsible authority.',good:false},
 {id:'public',label:'Publish only the variant calls',cue:'The raw reads would stay closed.',feedback:'Variant calls can still be sensitive. Unknown consent blocks this reuse question regardless of which files you release.',good:false},
 {id:'refer',label:'Pause and refer the consent question',cue:'The missing answer is about authority, not storage.',feedback:'Record the proposed method safely, but stop reuse and release until the responsible consent authority resolves the purpose. No click here clears that hold.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List sequence and variant file types; document the run; refer unknown consent and purpose outside this exercise.','Consent and approved purpose remain unknown. Refer to the project consent owner with a privacy specialist.','Variant file header only: ##fileformat=VCF; no variant rows'),
 'brain-maps':make('brain-maps','Brain images','Neuroimaging','Neural Imaging Group','Dr Ria Chen','The imaging group removed facial structure from brain scans today. Small companion JSON files remain with each image. A person still needs to check the images and companion fields for identifying details.','1,800 GiB of MRI images and companion JSON files. Invented files: scan-EXAMPLE.nii and scan-EXAMPLE.json. No image pixels or person details appear here.','mri-session-v1','defaced-mri-v2','Does removing facial structure finish the safety check?',[
 {id:'done',label:'Send the images to the vault now',cue:'The face is no longer visible.',feedback:'A processing run can miss a face, and companion fields may still identify someone. Ask people to check both before handoff.',good:false},
 {id:'sidecar',label:'Delete every companion file',cue:'Removing fields might avoid disclosure.',feedback:'Some fields explain how to use the scans. Review and remove unsafe fields instead of deleting all method information.',good:false},
 {id:'check',label:'Check images and companion files with reviewers',cue:'A tool result needs a human quality check.',feedback:'The steward checks the run and companion-file list. The privacy reviewer checks residual identifiers and intended use. Confirmed consent status alone does not finish either check.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List scans and companion files; request a human quality check and a privacy review; check file integrity.','','JSON sketch: {"DefacingRun":"unverified"}; no person fields')
};
const questions={
 'oral-heritage':{steward:'Does the corrected transcript point back to the recording and the correction method?',privacy:'Does limited consent cover the proposed description and the use of recordings?',community:'Can a title be found at all, and who may ask for recordings? Keep those decisions separate.'},
 'stellar-survey':{steward:'Which pipeline run and calibration inputs produced these images, and can a colleague trace them?'},
 'neighbourhood-voices':{steward:'Does the codebook explain how the new table was coded from the interviews?',privacy:'Does limited consent cover this coded table and this intended research use?'},
 'coastal-species':{steward:'Can the grid method be traced without exposing the exact sites?',privacy:'Has an outside specialist assessed whether the map or its description reveals a rare site?'},
 'variant-study':{steward:'Which caller version would make the proposed variant calls from these reads?',privacy:'Who outside this exercise can establish consent and an approved purpose before reuse?'},
 'brain-maps':{steward:'Which defacing run made these images, and which companion files belong with them?',privacy:'Did a person check the images and companion fields for remaining identifiers and intended use?'}
};
for(const [id,reviewQuestions] of Object.entries(questions))scenarios[id].reviewQuestions=reviewQuestions;
const outcomes={
 'oral-heritage':{steward:'The version link is only a draft until the correction log is checked.',privacy:'Limited consent needs a real reading before any proposed use.',community:'Keep the title private for now; a separate person decides requests for recordings.'},
 'stellar-survey':{steward:'The run reference is noted, but the calibration inputs and processing history still need checking.'},
 'neighbourhood-voices':{steward:'The codebook reference helps trace the coding, not the agreed use.',privacy:'Coded rows and voice files stay private while the consent scope is checked.'},
 'coastal-species':{steward:'The grid method is recorded, but a traceable method does not prove location safety.',privacy:'The outside location-risk assessment is still missing. Do not release the map.'},
 'variant-study':{steward:'The caller run can be documented while reuse stays paused.',privacy:'Unknown consent and purpose must go to the responsible authority. This answer does not clear the hold.'},
 'brain-maps':{steward:'The defacing run and companion files need a quality check against the actual images.',privacy:'A person must inspect residual image details and companion fields before any transfer.'}
};
for(const [id,reviewOutcome] of Object.entries(outcomes))scenarios[id].reviewOutcome=reviewOutcome;
export const roles={researcher:'Researcher',steward:'Data steward',privacy:'Privacy reviewer',community:'Community-appointed reviewer',curator:'Repository curator'};
