// All projects, people, files and services here are invented teaching examples.
const make=(id,title,discipline,group,person,arrival,files,from,to,question,choices,reviewers,candidate,checklist,hold='',sample='')=>({id,title,discipline,group,person,arrival,files,from,to,question,choices,reviewers,candidate,checklist,hold,sample});
export const scenarios={
 'oral-heritage':make('oral-heritage','Oral histories','History','Living Heritage Collective','Dr Tova Mer','Today your group corrected transcripts and wants to describe the collection. The recordings came with limited consent and community rules. Even a catalogue title might reveal something the community wants kept private.','Hundreds of gigabytes of voice recordings, transcript text and scanned images. Invented file names: clip-EXAMPLE.wav, transcript-EXAMPLE.txt, image-EXAMPLE.tiff. No voices or words appear here.','recordings-v1','curated-collection-v2','Who should decide whether anyone can find the description?',[
 {id:'publish',label:'Put up a public catalogue title now',cue:'A title might seem harmless.',feedback:'A catalogue title can reveal a person, place or tradition even when recordings stay closed. Take the title back for community review first.',good:false},
 {id:'private',label:'Keep the description private without asking the community',cue:'No one could find it.',feedback:'Keeping it private for now is safe, but the community should decide future discoverability. Ask its appointed reviewer rather than deciding for them.',good:false},
 {id:'ask',label:'Keep it private and ask the appointed reviewers',cue:'Description and file requests are separate questions.',feedback:'Keep the description private until the steward checks the correction, the privacy office reads the consent terms and the community-appointed body decides discovery. No file access follows from a title.',good:true}],['steward','privacy','community'],'Meridian Community-Governed Collection','List the invented files; request a check that copies stay unchanged; keep the description private; ask separately who may request recordings.','','transcript_id,language,consent_status (invented column names only)'),
 'stellar-survey':make('stellar-survey','Sky survey','Astronomy','Sky Survey Lab','Dr Ada Rell','The lab corrected a sky mosaic today. Another scientist wants the corrected images, but the processing run has not been linked to them. The collection is too large to assume an archive can take it.','A very large sky-image collection in astronomy image and chunked-array formats. Invented files: tile-EXAMPLE.fits, tile-EXAMPLE.zarr and pipeline-run-EXAMPLE.txt. No image pixels appear here.','sky-raw-v1','sky-calibrated-v2','What would let someone understand and store this correction?',[
 {id:'copy',label:'Send the corrected images alone',cue:'The pictures look ready.',feedback:'Without the processing run and calibration inputs, a colleague cannot explain the correction. Record the run and ask about archive capacity.',good:false},
 {id:'run',label:'Link the run and ask about archive capacity',cue:'The copy and its origin travel together.',feedback:'That connects old and new images to the method. The steward still checks the link and a curator must check space and file integrity.',good:true},
 {id:'wait',label:'Wait until every image has been checked',cue:'Checking files matters.',feedback:'Checks matter, but waiting does not record which run made the new images. Link the run first and arrange the checks.',good:false}],['steward'],'Meridian Large-Object Archive','List astronomy images and chunked-array objects; check processing history, file integrity and capacity.','','Astronomy image header sketch: SIMPLE = T; pixels omitted'),
 'neighbourhood-voices':make('neighbourhood-voices','Neighbourhood interviews','Social science','Urban Lives Group','Dr Malik Osei','Your team coded interviews about neighbourhood change today. The coded table sits beside voice recordings and a guide that explains each code. Interviewees agreed only to limited uses, so a coded row is not automatically safe to publish.','Dozens of gigabytes of recordings, text and coded tables. Invented files: audio-EXAMPLE.wav, guide-EXAMPLE.csv and memo-EXAMPLE.txt. No names or quotes appear here.','interviews-v1','coded-interviews-v2','Does coding the interviews make the result public?',[
 {id:'post',label:'Publish the coded table',cue:'It has no direct names.',feedback:'Codes can still point to someone, and limited consent does not become open consent when you code a table. Ask the privacy reviewer about this use.',good:false},
 {id:'delete',label:'Discard the codebook',cue:'Fewer files might feel safer.',feedback:'Without the guide to the codes, others cannot understand what the codes mean. Keep it restricted and ask which use consent covers.',good:false},
 {id:'scope',label:'Keep the table private and check the agreed use',cue:'The agreed purpose matters.',feedback:'That protects both the recordings and the coded table while a privacy reviewer can examine the limited consent. A private description is separate from file access.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List recordings, coded tables and the guide to their codes; ask about the agreed use; keep descriptions private; check file integrity.','','recording_id,codebook_version,consent_scope (invented column names only)'),
 'coastal-species':make('coastal-species','Coastal species','Ecology','Coastal Ecology Unit','Dr Paz Linn','The team replaced exact rare-species sites with larger map areas today. A published map could still reveal sites when combined with other information. No outside location-risk assessment has happened.','Hundreds of gigabytes of restricted tables and map images. Invented files: restricted-EXAMPLE.csv, area-EXAMPLE.csv and preview-EXAMPLE.tiff. No coordinates or sightings appear here.','observations-v1','generalised-coordinates-v2','Is a coarser map safe to share?',[
 {id:'map',label:'Publish the coarser map now',cue:'The exact points are gone.',feedback:'A map area or caption can still narrow down a rare site. An outside location-risk assessment must happen before release.',good:false},
 {id:'source',label:'Send restricted sites to a research partner for a check',cue:'Others could check the work.',feedback:'Exact sites create more risk. Keep the source restricted and ask an independent specialist to assess the coarser map and its description.',good:false},
 {id:'assess',label:'Keep both private and request a location-risk check',cue:'The map and its description both matter.',feedback:'The steward can document the map-area method, but only an outside location-risk assessment can resolve the release question. This exercise cannot clear that hold.',good:true}],['steward','privacy'],'Meridian General Archive','Keep raw sites apart from the grid; document the method; request an outside location-risk assessment before release.','An independent ecology location-risk specialist has not assessed the map and its description.','species_code,map_area,observation_month (invented column names only)'),
 'variant-study':make('variant-study','Variant study','Genomics','Human Variation Group','Dr Elin Roe','The group wants to reprocess a very large sequence collection today. A secure vault might hold the files, but the consent status is unknown. Storage capacity says nothing about whether this reuse is allowed.','Tens of thousands of gigabytes of sequence reads and files listing genetic differences. Invented files: reads-EXAMPLE.fastq, variants-EXAMPLE.vcf and run-EXAMPLE.txt. No genotypes or participant IDs appear here.','sequence-v1','variant-calls-v2','Does a suitable vault allow reprocessing or sharing?',[
 {id:'vault',label:'Use the secure vault and proceed',cue:'The files would stay protected.',feedback:'The vault may fit the files, but it cannot supply missing consent or an approved purpose. Pause reuse and refer the question to the responsible authority.',good:false},
 {id:'public',label:'Share only the genetic-difference list with collaborators',cue:'The raw reads would stay closed.',feedback:'Files listing genetic differences can still be sensitive. Unknown consent blocks this reuse question regardless of which files you release.',good:false},
 {id:'refer',label:'Pause and refer the consent question',cue:'The missing answer is about authority, not storage.',feedback:'Record the proposed method safely, but stop reuse and release until the responsible consent authority resolves the purpose. No click here clears that hold.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List sequence and variant file types; document the run; refer unknown consent and purpose outside this exercise.','Consent and approved purpose remain unknown. Refer to the project consent owner with a privacy specialist.','Genetic-difference file header only; no participant rows'),
 'brain-maps':make('brain-maps','Brain images','Neuroimaging','Neural Imaging Group','Dr Ria Chen','The imaging group removed facial structure from brain scans today. Small structured companion files remain with each image. A person still needs to check the images and companion fields for identifying details.','Thousands of gigabytes of brain scans and small structured companion files. Invented files: scan-EXAMPLE.nii and scan-EXAMPLE.json. No image pixels or person details appear here.','mri-session-v1','defaced-mri-v2','Does removing facial structure finish the safety check?',[
 {id:'done',label:'Send the images to the vault now',cue:'The face is no longer visible.',feedback:'A processing run can miss a face, and companion fields may still identify someone. Ask people to check both before handoff.',good:false},
 {id:'sidecar',label:'Delete every companion file',cue:'Removing fields might avoid disclosure.',feedback:'Some fields explain how to use the scans. Review and remove unsafe fields instead of deleting all method information.',good:false},
 {id:'check',label:'Check images and companion files with reviewers',cue:'A tool result needs a human quality check.',feedback:'The steward would check the run and companion-file list. The privacy reviewer would check residual identifiers and intended use. Confirmed consent status alone does not finish either check.',good:true}],['steward','privacy'],'Meridian Secure Data Vault','List scans and companion files; request a human quality check and a privacy review; check file integrity.','','Structured companion-file sketch: {"DefacingRun":"unverified"}; no person fields')
};
const questions={
 'oral-heritage':{steward:'Does the corrected transcript point back to the recording and the correction method?',privacy:'Does limited consent cover the proposed description and the use of recordings?',community:'Can a title be found at all, and who may ask for recordings? Keep those decisions separate.'},
 'stellar-survey':{steward:'Which pipeline run and calibration inputs produced these images, and can a colleague trace them?'},
 'neighbourhood-voices':{steward:'Does the guide to the codes explain how the new table was coded from the interviews?',privacy:'Does limited consent cover this coded table and this intended research use?'},
 'coastal-species':{steward:'Can the map-area method be traced without exposing the exact sites?',privacy:'Has an outside specialist assessed whether the map or its description reveals a rare site?'},
 'variant-study':{steward:'Which caller version would make the proposed genetic-difference list from these reads?',privacy:'Who outside this exercise can establish consent and an approved purpose before reuse?'},
 'brain-maps':{steward:'Which defacing run made these images, and which companion files belong with them?',privacy:'Did a person check the images and companion fields for remaining identifiers and intended use?'}
};
for(const [id,reviewQuestions] of Object.entries(questions))scenarios[id].reviewQuestions=reviewQuestions;
export const roles={researcher:'Researcher',steward:'Data steward',privacy:'Privacy reviewer',community:'Community-appointed reviewer',curator:'Repository curator'};

// These are bounded training responses, not evidence of an actual inspection.
const lessons={
 'oral-heritage':{card:'History · Dr Tova Mer, researcher. Corrected oral-history transcripts; decide whether the collection can be found.',risk:['A public title is now in the draft catalogue; it may expose a person or tradition. Nothing was published.','The draft closes discovery permanently without asking the community. Nothing was published.'],steward:['Draft link records the transcript correction; recording and correction log still need checking.','Need the correction log before describing the link.'],privacy:['Limited consent is not evidence for this proposed use; a real consent review remains open.','Need the actual consent terms and intended use.'],community:['Keep the title private; the appointed community body must decide discovery and recording requests separately.','Need the appointed community body to decide both questions.'],external:'The appointed community body must decide title visibility and recording requests; the privacy office must examine actual consent terms.'},
 'stellar-survey':{card:'Astronomy · Dr Ada Rell, researcher. Corrected sky images; decide what a colleague needs to reproduce them.',risk:['The draft package now omits the processing run, so the correction cannot be traced.','The draft postpones the run link, so the images remain unexplained.'],steward:['The proposed run reference links the two copies; calibration inputs and actual run log remain to be checked.','Need the calibration inputs and actual run log.'],external:'The archive curator must confirm capacity and verify the real file list and integrity.'},
 'neighbourhood-voices':{card:'Social science · Dr Malik Osei, researcher. Coded interviews; decide if a coded table can leave the team.',risk:['The draft marks the coded table public despite limited consent; coded rows may identify people. Nothing was published.','The draft removes the guide to the codes, so readers cannot interpret the coded table. Nothing was deleted.'],steward:['The private guide to the codes explains the proposed table; actual coding and source link remain unverified.','Need the codebook version and source link.'],privacy:['Keep the coded table and voices private; the consent owner must confirm this use against actual agreements.','Need the signed consent terms and proposed use before any decision.'],external:'The project consent owner and privacy office must compare the actual agreements with the intended coded-table use.'},
 'coastal-species':{card:'Ecology · Dr Paz Linn, researcher. Replaced rare-species sites with larger map areas; decide whether the map can be released.',risk:['The draft marks the coarser map public; other clues may reveal a rare site. Nothing was published.','The draft proposes giving a partner exact rare-species sites before the risk review. Nothing was shared.'],steward:['The proposed map-area method is described, but the source and actual transformation still need checking.','Need the actual transformation record without exposing sites.'],privacy:['A location-risk specialist has not assessed the map and caption; release remains blocked.','Need the outside location-risk assessment of map and description.'],external:'An independent ecology location-risk specialist must assess the actual map and description before release.'},
 'variant-study':{card:'Genomics · Dr Elin Roe, researcher. Plans to reprocess sequences; decide whether secure storage authorizes reuse.',risk:['The draft begins reuse on the strength of vault capacity alone; consent and purpose are unknown. No processing occurred.','The draft proposes sharing genetic-difference results with collaborators while consent is unknown. Nothing was shared.'],steward:['The proposed caller run can be documented, but no reuse is authorized.','Need a run specification while work remains paused.'],privacy:['Consent and approved purpose are unknown; the project consent owner must decide reuse.','Need the consent owner to establish purpose and authority.'],external:'The project consent owner and privacy specialist must establish consent and approved purpose before reuse or release.'},
 'brain-maps':{card:'Neuroimaging · Dr Ria Chen, researcher. Removed facial structure from scans; decide whether the copies can move.',risk:['The draft treats automated face removal as complete inspection; residual image or companion fields may identify someone. Nothing moved.','The draft deletes companion information needed to interpret scans. Nothing was deleted.'],steward:['The proposed processing run and companion list are recorded; actual images and files remain uninspected.','Need the processing log and actual companion-file list.'],privacy:['A trained image reviewer and privacy office must inspect scans and companion fields; this exercise did not.','Need human inspection of actual images and companion fields.'],external:'A trained image reviewer must inspect actual scans; the privacy office must inspect companion fields and intended use before transfer.'}
};
for(const [id,lesson] of Object.entries(lessons)){
 const c=scenarios[id];c.card=lesson.card;c.external=lesson.external;
 c.choices.filter(o=>!o.good).forEach((o,i)=>o.consequence=lesson.risk[i]);
 c.choices.find(o=>o.good).consequence='The draft keeps the proposed action private and routes the unresolved question to the named reviewers.';
 c.safePlans=[{id:'private-review',label:'Keep the proposed copy private and request the named checks'}, {id:'narrowed-review',label:'Revised private plan: document the method and request the missing evidence before any use'}];
 c.packagePlans=[{id:'inventory-pending',label:'Draft inventory only; checks outstanding'}, {id:'inventory-revised',label:'Revised inventory includes run link and requests capacity and integrity checks'}];
 c.reviewOptions={};for(const r of c.reviewers){
  const statements=lesson[r];c.reviewOptions[r]=[{id:`${r}-scope`,decision:r==='steward'?'noted':'needs-more',label:statements[0]}, {id:`${r}-evidence`,decision:'needs-more',label:statements[1]}];
 }
 c.curatorReasons=[{id:'capacity-pending',label:'Draft package recorded; actual capacity, file list and integrity still need checking.'}];
}
